# An example Dockerfile for local development.
# This will install civis-jupyter-notebook from disk from than from PyPI.
FROM python:3.10.4-slim-buster

ENV DEFAULT_KERNEL=python3

RUN apt-get update \
 && apt-get install -y --no-install-recommends git \
 && apt-get purge -y --auto-remove \
 && rm -rf /var/lib/apt/lists/*

COPY . /civis-jupyter-notebook
RUN pip install --no-cache-dir /civis-jupyter-notebook && \
    civis-jupyter-notebooks-install

# Add Tini
ENV TINI_VERSION=v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

EXPOSE 8888
WORKDIR /root/work
ENTRYPOINT ["/tini", "--"]
CMD ["civis-jupyter-notebooks-start"]
