#!/usr/bin/env/python

import os
from civis_jupyter_notebooks.git_utils import CivisGit, GitError
from civis_jupyter_notebooks import platform_persistence


if os.environ.get('GIT_REPO_URL'):
    try:
        platform_persistence.logger.info('cloning git repository')
        CivisGit().clone_repository()
        platform_persistence.logger.info('git repository cloned')
    except GitError as e:
        platform_persistence.logger.error(str(e))
        # TODO: Have some sort of check to stop the rest of the code from executing
